name: "Deploy"
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  # Generate a tailscale vpn auth key with oauth2 client
  generate-tailscale-authkey:
    runs-on: ubuntu-latest
    env:
      CLIENT_ID: ${{ secrets.TAILSCALE_OAUTH_CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.TAILSCALE_OAUTH_CLIENT_SECRET }}
    steps:
      - name: Generate Tailscale Auth Key
        run: |
          # Generate access token with Oauth2 client
          ACCESS_TOKEN=$(curl -d "client_id=${CLIENT_ID}" -d "client_secret=${CLIENT_SECRET}" "https://api.tailscale.com/api/v2/oauth/token" | jq -r '.access_token')
          # Then create a one-off auth key via API with the access token we previously created
          AUTH_KEY=$(curl --location 'https://api.tailscale.com/api/v2/tailnet/-/keys' \
            --header "Authorization: Bearer ${ACCESS_TOKEN}" \
            --header "Content-Type: application/json" \
            --data '{
              "capabilities": {
                "devices": {
                  "create": {
                    "ephemeral": true, # set the key to expire after session ends
                    "tags": ["tag:server"]
                  }
                }
              },
              "expirySeconds": 120}' \
              | jq -r ".key")
          
          # Save the auth key
          echo "AUTH_KEY=$AUTH_KEY" >> $GITHUB_OUTPUT
  
  # Authenticate tailscale against private deployment network
  # using previously created auth key
  authenticate-to-private-network:
    runs-on: ubuntu-latest
    needs: generate-tailscale-authkey
    env:
      # Get auth key from previous job
      TAILSCALE_AUTH_KEY: ${{ needs.generate-tailscale-authkey.outputs.AUTH_KEY }}
      TAILSCALE_UPGRADE: "1"
    steps:
      - name: Debug tailscale
        run: echo ${{ needs.generate-tailscale-authkey.outputs.AUTH_KEY }}
      - name: Install tailscale
        run: curl -fsSL https://tailscale.com/install.sh | sh
      - name: Start Tailscale
        run: sudo tailscale up --auth-key $TAILSCALE_AUTH_KEY
      - name: Tailscale status
        run: tailscale status
        
  # Now that we are connected to private network
  # we can deploy our infrastructure with terraform
  build-infra-with-terraform:
    name: "Terraform infrastructure"
    needs: authenticate-to-private-network
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      # Checkout repository code
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        
      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        if: github.event_name == 'pull_request'
        run: terraform plan -no-color -input=false
        continue-on-error: true

      - name: Update Pull Request
        uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`

            <details><summary>Show Plan</summary>

            \`\`\`\n
            ${process.env.PLAN}
            \`\`\`

            </details>

            *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      # If terraform previously failed abort pipeline
      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      # Deploy with terraform on pushes to main branch
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false
        env:
          TF_VAR_proxmox_api_url: ${{ secrets.PROXMOX_API_URL }}
          TF_VAR_proxmox_api_token_id: ${{ secrets.PROXMOX_API_TOKEN_ID }}
          TF_VAR_proxmox_api_token_secret: ${{ secrets.PROXMOX_API_TOKEN_SECRET }}
          TF_VAR_ciuser: ${{ secrets.CI_USER }}
          TF_VAR_ipconfig0: ${{ secrets.IPCONFIG0 }}
          TF_VAR_ssh_keys: ${{ secrets.SSH_KEY }}
